# Codecov configuration for JSBSim
# See: https://docs.codecov.com/docs/codecov-yaml

coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%
        base: auto
    patch:
      default:
        target: 80%
        threshold: 1%
        base: auto

  ignore:
    # Don't require test files themselves to be tested
    - "tests/test_*.py"
    - "tests/Test*.py"
    - "tests/Check*.py"
    # Legacy test infrastructure
    - "tests/__pycache__"
    - "tests/*/__pycache__"
    # Build artifacts
    - "build"
    - "build-*"
    - ".local"

comment:
  layout: "diff, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

flags:
  python:
    paths:
      - tests/
      - python/
    carryforward: true
